import numpy as np
x=0
masks = [[
    np.array([[0, x, 1],
              [0, 1, 1],
              [0, x, 1]], np.uint8),
    np.array([[1, x, 0],
              [1, 0, 0],
              [1, x, 0]], np.uint8),
    ],
    [
    np.array([[0, 0, x],
              [0, 1, 1],
              [x, 1, 1]], np.uint8),
    np.array([[1, 1, x],
              [1, 0, 0],
              [x, 0, 0]], np.uint8),
    ],
    [
    np.array([[0, 0, 0],
              [x, 1, x],
              [1, 1, 1]], np.uint8),
    np.array([[1, 1, 1],
              [x, 0, x],
              [0, 0, 0]], np.uint8),
    ],
    [
    np.array([[x, 0, 0],
              [1, 1, 0],
              [1, 1, x]], np.uint8),
    np.array([[x, 1, 1],
              [0, 0, 1],
              [0, 0, x]], np.uint8),
    ],
    [
    np.array([[1, x, 0],
              [1, 1, 0],
              [1, x, 0]], np.uint8),
    np.array([[0, x, 1],
              [0, 0, 1],
              [0, x, 1]], np.uint8),
    ],
    [
    np.array([[1, 1, x],
              [1, 1, 0],
              [x, 0, 0]], np.uint8),
    np.array([[0, 0, x],
              [0, 0, 1],
              [x, 1, 1]], np.uint8),
    ],
    [
    np.array([[1, 1, 1],
              [x, 1, x],
              [0, 0, 0]], np.uint8),
    np.array([[0, 0, 0],
              [x, 0, x],
              [1, 1, 1]], np.uint8),
    ],
    [
    np.array([[x, 1, 1],
              [0, 1, 1],
              [0, 0, x]], np.uint8),
    np.array([[x, 0, 0],
              [1, 0, 0],
              [1, 1, x]], np.uint8),
    ],
]
